export interface ServiceData {
  serviceName: string;
  heroDescription: string;
  overview: string;
  features: string[];
  benefits: { title: string; description: string; icon: string }[];
  process: { step: number; title: string; description: string }[];
  faq: { question: string; answer: string }[];
  platforms?: string[];
}

export const servicePages: Record<string, ServiceData> = {
  'amazon-account-launch': {
    serviceName: 'Amazon Account Launch',
    heroDescription: 'Complete Amazon seller account setup and launch service for new and existing businesses.',
    overview: 'We handle your complete Amazon seller account setup from start to finish. From documentation to brand registry, our experts ensure a smooth launch so you can start selling quickly and compliantly on India\'s largest marketplace.',
    features: [
      'End-to-end account registration with all required documents',
      'GSTIN, PAN, and bank account verification support',
      'Initial product listing and catalog setup included',
      'Amazon Brand Registry assistance',
      'Dedicated account manager for smooth launch',
      'Tax registration and compliance guidance',
    ],
    benefits: [
      { title: 'Expert Guidance', description: 'Our team has launched 100+ Amazon seller accounts. We know the exact requirements and common pitfalls to avoid.', icon: 'Check' },
      { title: 'Faster Setup', description: 'Get your account live in 3-7 business days instead of weeks of trial and error on your own.', icon: 'Check' },
      { title: 'Full Compliance', description: 'We ensure all documentation meets Amazon\'s standards, reducing rejection risk.', icon: 'Check' },
      { title: 'Brand Protection', description: 'Brand Registry setup from day one to protect your intellectual property.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Document Collection', description: 'We gather all required documents including GSTIN, PAN, bank details, and product information.' },
      { step: 2, title: 'Account Verification', description: 'Submit and verify your Amazon seller account with proper documentation.' },
      { step: 3, title: 'Listing Setup', description: 'Create initial product listings with optimized titles, images, and descriptions.' },
      { step: 4, title: 'Go Live', description: 'Launch your store with Brand Registry and start selling on Amazon.' },
    ],
    faq: [
      { question: 'What documents are needed for Amazon account setup?', answer: 'You need GSTIN, PAN card, bank account details, cancelled cheque, and product details with images. Our team will guide you through each requirement.' },
      { question: 'How long does Amazon account setup take?', answer: 'Account setup typically takes 3-7 business days, depending on document verification speed and Amazon\'s review process.' },
      { question: 'Can you launch accounts for individuals too?', answer: 'Yes, we support both individual and business entity (proprietorship, partnership, Pvt Ltd) Amazon seller accounts.' },
    ],
    platforms: ['Amazon'],
  },
  'flipkart-account-launch': {
    serviceName: 'Flipkart Account Launch',
    heroDescription: 'Hassle-free Flipkart seller account registration and launch service with full listing setup.',
    overview: 'Get your Flipkart seller account up and running quickly with our complete launch service. We handle registration, catalog onboarding, and initial setup so you can start selling on India\'s homegrown marketplace.',
    features: [
      'Complete Flipkart seller registration from scratch',
      'Product listing and catalog onboarding',
      'Flipkart Plus eligibility assessment',
      'Payment and logistics setup support',
      'Initial performance optimization',
      'Brand portal registration assistance',
    ],
    benefits: [
      { title: 'Quick Registration', description: 'Our streamlined process gets your Flipkart account approved faster with fewer rejections.', icon: 'Check' },
      { title: 'Catalog Expertise', description: 'We create Flipkart-optimized listings that comply with their unique catalog requirements.', icon: 'Check' },
      { title: 'Logistics Setup', description: 'Proper configuration of Flipkart Fulfillment or self-ship logistics from day one.', icon: 'Check' },
      { title: 'Growth Ready', description: 'Your account is optimized for Flipkart\'s algorithms from the start.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Registration', description: 'Complete Flipkart seller hub registration with business details.' },
      { step: 2, title: 'Verification', description: 'Document verification and business detail confirmation.' },
      { step: 3, title: 'Catalog Setup', description: 'Product listing creation with Flipkart-compliant descriptions.' },
      { step: 4, title: 'Launch', description: 'Go live and start selling with optimized settings.' },
    ],
    faq: [
      { question: 'What are Flipkart\'s seller requirements?', answer: 'You need GST registration, PAN card, bank account, and address proof. Products must meet Flipkart\'s quality standards.' },
      { question: 'How is Flipkart different from Amazon?', answer: 'Flipkart has different listing requirements, fee structures, and customer demographics. We optimize for both platforms uniquely.' },
      { question: 'Can I sell on both Amazon and Flipkart?', answer: 'Absolutely! We recommend multi-platform selling and can launch both accounts simultaneously.' },
    ],
    platforms: ['Flipkart'],
  },
  'meesho-account-launch': {
    serviceName: 'Meesho Account Launch',
    heroDescription: 'Get your Meesho seller account set up quickly with complete catalog and pricing strategy.',
    overview: 'Launch your Meesho seller account with our expert setup service. We handle registration, bulk catalog upload, pricing strategy, and logistics understanding so you can tap into Meesho\'s massive reseller network.',
    features: [
      'Zero commission platform setup and strategy guidance',
      'Catalog and product upload in bulk',
      'Pricing and margin optimization for Meesho market',
      'Return policy and logistics understanding',
      'Order management system setup',
    ],
    benefits: [
      { title: 'Zero Commission Model', description: 'Meesho\'s unique zero-commission model requires different pricing strategy. We help you price profitably.', icon: 'Check' },
      { title: 'Bulk Upload', description: 'Upload hundreds of products efficiently with our bulk catalog tools.', icon: 'Check' },
      { title: 'Reseller Network', description: 'Optimize listings for Meesho\'s unique reseller-driven marketplace.', icon: 'Check' },
      { title: 'Margin Protection', description: 'Smart pricing that maintains healthy margins while staying competitive.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Account Setup', description: 'Register and verify your Meesho supplier account.' },
      { step: 2, title: 'Catalog Creation', description: 'Build product catalog optimized for Meesho\'s audience.' },
      { step: 3, title: 'Pricing Strategy', description: 'Set competitive prices that protect your margins.' },
      { step: 4, title: 'Go Live', description: 'Start receiving orders through Meesho\'s reseller network.' },
    ],
    faq: [
      { question: 'Is Meesho really commission-free?', answer: 'Yes, Meesho charges 0% commission. You only pay shipping costs on orders.' },
      { question: 'How is selling on Meesho different?', answer: 'Meesho uses a reseller model where individuals share your products. Pricing and packaging must account for this.' },
      { question: 'What products sell best on Meesho?', answer: 'Fashion, home decor, kitchen items, and accessories perform very well on Meesho.' },
    ],
    platforms: ['Meesho'],
  },
  'jiomart-account-launch': {
    serviceName: 'JioMart Account Launch',
    heroDescription: 'Launch your JioMart seller account with complete onboarding support.',
    overview: 'Tap into Reliance JioMart\'s rapidly growing customer base with our complete seller onboarding service. We handle documentation, product listing, and first-sale optimization for this emerging marketplace.',
    features: [
      'Complete JioMart seller registration',
      'Product catalog and listing setup',
      'Pricing strategy for JioMart customers',
      'Integration with JioMart fulfillment',
      'Performance optimization for visibility',
    ],
    benefits: [
      { title: 'Early Mover Advantage', description: 'JioMart is growing fast. Early sellers benefit from less competition and growing traffic.', icon: 'Check' },
      { title: 'Reliance Ecosystem', description: 'Access to Reliance\'s massive customer base across Jio and retail networks.', icon: 'Check' },
      { title: 'Quick Onboarding', description: 'Our relationship with JioMart team ensures faster account approval.', icon: 'Check' },
      { title: 'Local Market Focus', description: 'Optimized for JioMart\'s focus on tier-2 and tier-3 city customers.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Registration', description: 'Complete JioMart seller registration with business details.' },
      { step: 2, title: 'Verification', description: 'Document and business verification process.' },
      { step: 3, title: 'Catalog Setup', description: 'Create product listings for JioMart platform.' },
      { step: 4, title: 'Launch', description: 'Go live and start selling on JioMart.' },
    ],
    faq: [
      { question: 'What is JioMart marketplace?', answer: 'JioMart is Reliance\'s eCommerce platform, rapidly expanding across India with focus on grocery, FMCG, and general merchandise.' },
      { question: 'How do I become a JioMart seller?', answer: 'Register on JioMart seller portal with GST, PAN, and bank details. We handle the entire process for you.' },
      { question: 'What are JioMart\'s commission rates?', answer: 'Commission rates vary by category, typically between 5-15%. We help you price accordingly.' },
    ],
    platforms: ['JioMart'],
  },
  'amazon-account-management': {
    serviceName: 'Amazon Account Management',
    heroDescription: 'Monthly Amazon account management for sustained growth and performance.',
    overview: 'Comprehensive monthly management of your Amazon seller account. From daily health monitoring to listing optimization, review management, and sales growth — we handle everything so you can focus on your products.',
    features: [
      'Daily account health monitoring',
      'Keyword-rich listing optimization',
      'Inventory and replenishment alerts',
      'Review and feedback management',
      'Monthly performance reports',
      'Return and refund handling support',
    ],
    benefits: [
      { title: 'Account Health', description: 'Daily monitoring ensures your account stays in perfect health with no policy violations.', icon: 'Check' },
      { title: 'Listing Optimization', description: 'Continuous keyword research and listing updates to improve rankings and conversions.', icon: 'Check' },
      { title: 'Sales Growth', description: 'Data-driven strategies to increase your monthly sales and profitability on Amazon.', icon: 'Check' },
      { title: 'Time Savings', description: 'Free up your time while experts handle the daily complexities of Amazon selling.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Audit', description: 'Complete account audit and health assessment.' },
      { step: 2, title: 'Strategy', description: 'Custom growth plan based on audit findings.' },
      { step: 3, title: 'Management', description: 'Daily monitoring and optimization execution.' },
      { step: 4, title: 'Reporting', description: 'Monthly performance reports and strategy adjustments.' },
    ],
    faq: [
      { question: 'What does monthly management include?', answer: 'Daily account monitoring, listing optimization, inventory management, review management, PPC oversight, and monthly reporting.' },
      { question: 'How do you improve sales?', answer: 'We use keyword optimization, A/B testing, competitive analysis, and data-driven pricing strategies to boost visibility and conversions.' },
      { question: 'Can I see results quickly?', answer: 'Most clients see improvements within 30-60 days, depending on their product category and competition level.' },
    ],
    platforms: ['Amazon'],
  },
  'flipkart-account-management': {
    serviceName: 'Flipkart Account Management',
    heroDescription: 'Expert Flipkart account management to boost sales and account health.',
    overview: 'End-to-end management of your Flipkart seller account. We handle listing optimization, account health monitoring, ad management, and growth strategy to maximize your Flipkart revenue.',
    features: [
      'Daily Flipkart account health monitoring',
      'Listing optimization for Flipkart search',
      'Flipkart Ads campaign management',
      'Inventory management and alerts',
      'Performance improvement planning',
      'Monthly growth reports',
    ],
    benefits: [
      { title: 'Platform Expertise', description: 'Deep understanding of Flipkart\'s unique algorithms and seller policies.', icon: 'Check' },
      { title: 'Search Ranking', description: 'Optimize listings to rank higher in Flipkart search results.', icon: 'Check' },
      { title: 'Ad ROI', description: 'Maximize return on your Flipkart Ads investment with expert management.', icon: 'Check' },
      { title: 'Growth Focus', description: 'Monthly strategy adjustments based on performance data and market trends.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Audit', description: 'Assess current account health and performance.' },
      { step: 2, title: 'Optimize', description: 'Improve listings, pricing, and account settings.' },
      { step: 3, title: 'Manage', description: 'Ongoing daily monitoring and optimization.' },
      { step: 4, title: 'Grow', description: 'Scale winning strategies and expand your catalog.' },
    ],
    faq: [
      { question: 'How is Flipkart management different from Amazon?', answer: 'Flipkart has different listing requirements, search algorithms, and advertising platforms. Our team specializes in both.' },
      { question: 'Do you handle Flipkart Fulfillment?', answer: 'Yes, we help manage your Flipkart Fulfillment (FKF) inventory and logistics.' },
      { question: 'What metrics do you track?', answer: 'We track listing quality, search ranking, conversion rate, return rate, customer ratings, and overall growth.' },
    ],
    platforms: ['Flipkart'],
  },
  'meesho-account-management': {
    serviceName: 'Meesho Account Management',
    heroDescription: 'Dedicated Meesho account management for maximum reseller network growth.',
    overview: 'Specialized management for your Meesho supplier account. We optimize your catalog for the unique reseller-driven marketplace, manage pricing strategy, and help you scale within Meesho\'s zero-commission model.',
    features: [
      'Catalog optimization for resellers',
      'Pricing and margin management',
      'Order processing support',
      'Return rate reduction strategies',
      'New product launch support',
      'Monthly performance analysis',
    ],
    benefits: [
      { title: 'Reseller Optimization', description: 'Listings designed to be shared and sold by Meesho\'s extensive reseller network.', icon: 'Check' },
      { title: 'Margin Management', description: 'Smart pricing that attracts resellers while protecting your profits.', icon: 'Check' },
      { title: 'Scale Support', description: 'Handle increasing order volumes without operational stress.', icon: 'Check' },
      { title: 'Trend Adaptation', description: 'Quick catalog updates based on trending products and seasons.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Analysis', description: 'Review current catalog performance and margins.' },
      { step: 2, title: 'Optimization', description: 'Improve listings, pricing, and catalog structure.' },
      { step: 3, title: 'Scaling', description: 'Add new products and expand reseller reach.' },
      { step: 4, title: 'Maintenance', description: 'Ongoing management and performance improvement.' },
    ],
    faq: [
      { question: 'How do you improve Meesho sales?', answer: 'We optimize product listings for resellers, adjust pricing strategy, and expand your catalog with trending products.' },
      { question: 'What is the typical return rate on Meesho?', answer: 'Return rates on Meesho are typically 15-25%. We help reduce this through better product descriptions and quality control.' },
      { question: 'Can you manage high order volumes?', answer: 'Yes, we specialize in helping suppliers scale from hundreds to thousands of daily orders.' },
    ],
    platforms: ['Meesho'],
  },
  'jiomart-account-management': {
    serviceName: 'JioMart Account Management',
    heroDescription: 'Professional JioMart seller account management for consistent growth.',
    overview: 'Complete management of your JioMart seller account as the platform grows. We handle catalog management, pricing optimization, and performance tracking to ensure you maximize this emerging marketplace opportunity.',
    features: [
      'JioMart catalog management',
      'Price optimization for JioMart customers',
      'Account health monitoring',
      'Inventory and fulfillment coordination',
      'Monthly growth strategy reviews',
    ],
    benefits: [
      { title: 'Growth Focus', description: 'Strategies tailored to JioMart\'s unique customer base and growth trajectory.', icon: 'Check' },
      { title: 'Competitive Pricing', description: 'Dynamic pricing that wins the Buy Box while maintaining margins.', icon: 'Check' },
      { title: 'Early Advantage', description: 'Being an early optimized seller on a growing platform has huge advantages.', icon: 'Check' },
      { title: 'Multi-platform Sync', description: 'Manage inventory and pricing across JioMart and other platforms seamlessly.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Setup Review', description: 'Audit current account setup and performance.' },
      { step: 2, title: 'Optimization', description: 'Improve catalog, pricing, and fulfillment.' },
      { step: 3, title: 'Monitoring', description: 'Track performance and account health daily.' },
      { step: 4, title: 'Scaling', description: 'Expand catalog and grow market share.' },
    ],
    faq: [
      { question: 'Is JioMart worth investing in?', answer: 'Yes, with Reliance\'s backing and rapid expansion, JioMart is becoming a major eCommerce player in India.' },
      { question: 'What categories perform best?', answer: 'Grocery, FMCG, electronics, fashion, and home essentials are top categories on JioMart.' },
      { question: 'How does fulfillment work?', answer: 'JioMart offers both platform fulfillment and self-ship options. We help you choose the best model.' },
    ],
    platforms: ['JioMart'],
  },
  'amazon-advertisement': {
    serviceName: 'Amazon Advertisement',
    heroDescription: 'Expert Amazon PPC campaign management to maximize your ROAS and grow sales.',
    overview: 'Professional management of Amazon advertising campaigns including Sponsored Products, Sponsored Brands, and Sponsored Display. We optimize your ad spend for maximum return and scalable sales growth.',
    features: [
      'Campaign audit and strategy creation',
      'Sponsored Products (SP) management',
      'Sponsored Brands (SB) setup and optimization',
      'ACOS/ROAS monitoring and optimization',
      'Negative keyword management',
      'Weekly performance reports',
    ],
    benefits: [
      { title: 'Lower ACOS', description: 'Our optimization strategies typically reduce ACOS by 20-40% within the first month.', icon: 'Check' },
      { title: 'Higher ROAS', description: 'Data-driven bidding and targeting to get more sales per rupee spent.', icon: 'Check' },
      { title: 'Scalable Growth', description: 'Campaign structures designed to scale with your growing catalog.', icon: 'Check' },
      { title: 'Full Transparency', description: 'Weekly reports showing exactly where your money goes and what it returns.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Audit', description: 'Analyze current campaigns and identify improvement areas.' },
      { step: 2, title: 'Strategy', description: 'Create custom campaign structure and bidding strategy.' },
      { step: 3, title: 'Optimize', description: 'Daily monitoring and continuous optimization.' },
      { step: 4, title: 'Scale', description: 'Expand winning campaigns and increase profitable spend.' },
    ],
    faq: [
      { question: 'What is a good ACOS for Amazon India?', answer: 'A good ACOS varies by category but typically ranges from 10-25% for established products and 25-40% for new launches.' },
      { question: 'How long before I see results?', answer: 'Initial optimizations show results within 1-2 weeks, with significant improvements by week 4.' },
      { question: 'Do you handle all ad types?', answer: 'Yes, we manage Sponsored Products, Sponsored Brands, Sponsored Display, and Stores.' },
    ],
    platforms: ['Amazon'],
  },
  'flipkart-advertisement': {
    serviceName: 'Flipkart Advertisement',
    heroDescription: 'Data-driven Flipkart Ads management for maximum visibility and sales.',
    overview: 'Expert management of Flipkart advertising campaigns including Product Listings Ads and Brand Ads. We optimize your ad spend to drive more visibility, clicks, and conversions on Flipkart.',
    features: [
      'Flipkart Product Listing Ads (PLA) management',
      'Brand Ads campaign setup',
      'Bid optimization and monitoring',
      'Keyword research and targeting',
      'Campaign performance reporting',
      'Budget allocation strategy',
    ],
    benefits: [
      { title: 'Increased Visibility', description: 'Get your products seen by more Flipkart shoppers with optimized ad placements.', icon: 'Check' },
      { title: 'Better Conversions', description: 'Target the right customers at the right time in their purchase journey.', icon: 'Check' },
      { title: 'Cost Efficiency', description: 'Optimized bidding reduces wasted spend and improves cost per conversion.', icon: 'Check' },
      { title: 'Competitive Edge', description: 'Stay ahead of competitors with strategic ad placements and targeting.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Analysis', description: 'Review current ad performance and competitive landscape.' },
      { step: 2, title: 'Setup', description: 'Create optimized campaign structure with proper targeting.' },
      { step: 3, title: 'Manage', description: 'Daily monitoring and bid adjustments for optimal performance.' },
      { step: 4, title: 'Report', description: 'Regular performance reports and strategy refinements.' },
    ],
    faq: [
      { question: 'What are Flipkart Product Listing Ads?', answer: 'PLAs appear in search results and category pages, helping your products get discovered by active shoppers.' },
      { question: 'How is Flipkart advertising different from Amazon?', answer: 'Flipkart has different ad formats, bidding systems, and audience behavior. We optimize specifically for Flipkart.' },
      { question: 'What budget do I need?', answer: 'We work with budgets starting from 10,000/month and scale based on performance.' },
    ],
    platforms: ['Flipkart'],
  },
  'meesho-advertisement': {
    serviceName: 'Meesho Advertisement',
    heroDescription: 'Strategic Meesho product ads to reach more resellers and drive orders.',
    overview: 'Optimize your product visibility on Meesho with targeted advertising. We help you reach more resellers and customers through Meesho\'s advertising platform while maintaining healthy margins.',
    features: [
      'Meesho product ad campaign setup',
      'Ad spend optimization',
      'Targeted visibility campaigns',
      'Performance tracking and reporting',
      'ROI-focused bidding strategy',
    ],
    benefits: [
      { title: 'More Resellers', description: 'Increased visibility means more resellers sharing and selling your products.', icon: 'Check' },
      { title: 'Better Margins', description: 'Strategic ad spend that maintains profitability on Meesho\'s zero-commission model.', icon: 'Check' },
      { title: 'Quick Results', description: 'Meesho ads often show results faster due to the platform\'s social commerce model.', icon: 'Check' },
      { title: 'Growth Support', description: 'Scale your ad spend as your catalog and order volume grow.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Setup', description: 'Create ad account and initial campaigns.' },
      { step: 2, title: 'Launch', description: 'Start ads with optimized product selection and bidding.' },
      { step: 3, title: 'Optimize', description: 'Monitor and adjust for best performing products.' },
      { step: 4, title: 'Scale', description: 'Increase spend on winning campaigns and products.' },
    ],
    faq: [
      { question: 'How do Meesho ads work?', answer: 'Meesho ads boost your product visibility in the app, helping resellers discover and share your products.' },
      { question: 'Are Meesho ads worth it?', answer: 'Yes, especially for trending categories. Ads can significantly increase your daily order volume.' },
      { question: 'What is the minimum ad budget?', answer: 'We recommend starting with 5,000-10,000/month and scaling based on results.' },
    ],
    platforms: ['Meesho'],
  },
  'jiomart-advertisement': {
    serviceName: 'JioMart Advertisement',
    heroDescription: 'JioMart advertising solutions to grow your brand on this emerging platform.',
    overview: 'Get ahead of the competition with strategic advertising on JioMart. We create and manage campaigns that increase your product visibility and drive sales on Reliance\'s growing eCommerce platform.',
    features: [
      'JioMart ad campaign creation and management',
      'Product visibility optimization',
      'Performance-based budget allocation',
      'Competitive positioning strategy',
      'Regular performance analytics',
    ],
    benefits: [
      { title: 'First Mover Advantage', description: 'Less competition on JioMart ads means lower costs and better visibility early on.', icon: 'Check' },
      { title: 'Growing Audience', description: 'Access JioMart\'s rapidly expanding customer base across India.', icon: 'Check' },
      { title: 'Strategic Positioning', description: 'Position your brand effectively on a platform backed by Reliance.', icon: 'Check' },
      { title: 'Cost Efficiency', description: 'Lower CPCs and CPMs compared to established platforms while audience grows.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Strategy', description: 'Develop advertising strategy for JioMart platform.' },
      { step: 2, title: 'Setup', description: 'Create campaigns and set targeting parameters.' },
      { step: 3, title: 'Launch', description: 'Start advertising and monitor initial performance.' },
      { step: 4, title: 'Optimize', description: 'Continuous improvement based on performance data.' },
    ],
    faq: [
      { question: 'Does JioMart have an advertising platform?', answer: 'Yes, JioMart offers advertising options for sellers to boost product visibility.' },
      { question: 'What products should I advertise?', answer: 'Focus on your best sellers and products with healthy margins that appeal to JioMart\'s audience.' },
      { question: 'How do you track ROI?', answer: 'We track ad spend, impressions, clicks, and attributed sales to calculate clear ROI.' },
    ],
    platforms: ['JioMart'],
  },
  'accounting-taxation': {
    serviceName: 'Accounting & Taxation',
    heroDescription: 'Complete GST registration, filing, ITR, and accounting for online sellers.',
    overview: 'End-to-end accounting and taxation services for eCommerce sellers and digital businesses. From GST registration to monthly filing, income tax returns, and bookkeeping — we keep your finances compliant and organized.',
    features: [
      'GST registration and GSTIN setup',
      'Monthly/quarterly GST return filing',
      'Income tax return (ITR) filing',
      'Bookkeeping and ledger management',
      'TDS management and compliance',
      'E-way bill generation support',
    ],
    benefits: [
      { title: 'Full Compliance', description: 'Stay fully compliant with all GST and income tax regulations. No penalties, no missed deadlines.', icon: 'Check' },
      { title: 'Time Savings', description: 'Focus on growing your business while we handle the complex tax work.', icon: 'Check' },
      { title: 'Expert Advice', description: 'Get professional tax planning advice to optimize your tax liability legally.', icon: 'Check' },
      { title: 'Organized Records', description: 'Clean, organized financial records ready for any audit or loan application.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Consultation', description: 'Understand your business structure and tax requirements.' },
      { step: 2, title: 'Registration', description: 'Complete GST registration and obtain GSTIN if needed.' },
      { step: 3, title: 'Management', description: 'Monthly bookkeeping and timely return filing.' },
      { step: 4, title: 'Compliance', description: 'Annual ITR filing and ongoing compliance support.' },
    ],
    faq: [
      { question: 'Do I need GST for selling online?', answer: 'Yes, GST registration is mandatory for eCommerce sellers in India regardless of turnover threshold.' },
      { question: 'What GST returns do I need to file?', answer: 'Typically GSTR-1 (monthly/quarterly outward supplies), GSTR-3B (monthly summary return), and GSTR-9 (annual return).' },
      { question: 'Can you handle multiple GSTINs?', answer: 'Yes, we manage accounting and compliance for businesses with multiple GST registrations across states.' },
    ],
    platforms: ['Amazon', 'Flipkart', 'Meesho', 'JioMart'],
  },
  'website-development': {
    serviceName: 'Website Development',
    heroDescription: 'Professional WordPress and Shopify eCommerce website development.',
    overview: 'Build a stunning, fast, and conversion-optimized website for your brand. We specialize in WordPress and Shopify development with mobile-first design, SEO-ready structure, and seamless payment integration.',
    features: [
      'Custom WordPress or Shopify design',
      'Mobile-first responsive development',
      'SEO-ready structure and metadata',
      'Payment gateway integration (Razorpay, PayU)',
      'WooCommerce / Shopify store setup',
      '6-month maintenance support included',
    ],
    benefits: [
      { title: 'Professional Design', description: 'Custom designs that reflect your brand and convert visitors into customers.', icon: 'Check' },
      { title: 'Mobile Optimized', description: 'Every site is built mobile-first for the best experience on any device.', icon: 'Check' },
      { title: 'SEO Ready', description: 'Clean code, fast loading, and proper structure for search engine visibility.', icon: 'Check' },
      { title: 'Easy Management', description: 'User-friendly CMS so you can update content without technical knowledge.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Discovery', description: 'Understand your brand, goals, and requirements.' },
      { step: 2, title: 'Design', description: 'Create wireframes and visual design for approval.' },
      { step: 3, title: 'Development', description: 'Build the site with clean, optimized code.' },
      { step: 4, title: 'Launch', description: 'Test, deploy, and provide training for your team.' },
    ],
    faq: [
      { question: 'Which platform is better — WordPress or Shopify?', answer: 'WordPress offers more flexibility and lower ongoing costs. Shopify is easier to manage and great for pure eCommerce. We help you choose based on your needs.' },
      { question: 'How long does website development take?', answer: 'A standard business website takes 2-3 weeks. An eCommerce store typically takes 3-5 weeks depending on catalog size.' },
      { question: 'Do you provide website maintenance?', answer: 'Yes, we include 6 months of free maintenance and offer affordable ongoing support packages.' },
    ],
    platforms: [],
  },
  'brand-store': {
    serviceName: 'Brand Store Design',
    heroDescription: 'Design and launch your official Brand Store on Amazon and Flipkart.',
    overview: 'Create a premium branded shopping experience with custom Brand Stores on Amazon and Flipkart. We design and build immersive brand destinations that build trust, showcase your full catalog, and drive more conversions.',
    features: [
      'Custom Amazon Brand Store design',
      'Flipkart Brand Hub setup',
      'Multi-page store architecture',
      'Rich media and video integration',
      'Mobile-optimized layouts',
      'Performance tracking setup',
    ],
    benefits: [
      { title: 'Brand Trust', description: 'A professional Brand Store builds instant credibility with shoppers.', icon: 'Check' },
      { title: 'Higher Conversions', description: 'Branded stores typically see 15-30% higher conversion rates.', icon: 'Check' },
      { title: 'Full Catalog Showcase', description: 'Display your complete product range in an organized, shoppable format.', icon: 'Check' },
      { title: 'Competitive Edge', description: 'Stand out from generic listings with a premium brand presence.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Brand Analysis', description: 'Understand your brand identity and goals.' },
      { step: 2, title: 'Design', description: 'Create custom store layout and visual design.' },
      { step: 3, title: 'Build', description: 'Construct the store with approved designs and content.' },
      { step: 4, title: 'Launch', description: 'Submit for approval and go live.' },
    ],
    faq: [
      { question: 'Do I need Brand Registry for an Amazon Brand Store?', answer: 'Yes, Brand Registry is required. We can help you obtain it if you haven\'t already.' },
      { question: 'How long does Brand Store creation take?', answer: 'Typically 1-2 weeks from design approval to live store.' },
      { question: 'Can I update my Brand Store later?', answer: 'Yes, we can update and refresh your Brand Store content anytime.' },
    ],
    platforms: ['Amazon', 'Flipkart'],
  },
  'brand-logo-design': {
    serviceName: 'Brand Logo Design',
    heroDescription: 'Professional logo design and brand identity for your business.',
    overview: 'Get a memorable, professional logo and complete brand identity package that makes your business stand out. From logo concepts to brand guidelines, we create visual identities that resonate with your target audience.',
    features: [
      'Multiple logo design concepts',
      'Unlimited revisions on chosen concept',
      'Complete brand color palette',
      'Typography selection',
      'Brand usage guidelines',
      'All file formats (AI, EPS, PNG, JPG, SVG)',
    ],
    benefits: [
      { title: 'Professional Identity', description: 'A professional logo instantly elevates your brand perception and trustworthiness.', icon: 'Check' },
      { title: 'Memorable Design', description: 'Unique, creative designs that customers remember and recognize.', icon: 'Check' },
      { title: 'Versatile Files', description: 'Logo files in every format needed for web, print, merchandise, and more.', icon: 'Check' },
      { title: 'Brand Consistency', description: 'Complete guidelines ensure consistent brand usage across all channels.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Brief', description: 'Understand your brand, audience, and design preferences.' },
      { step: 2, title: 'Concepts', description: 'Create 3-5 unique logo design concepts.' },
      { step: 3, title: 'Refinement', description: 'Refine the chosen concept with your feedback.' },
      { step: 4, title: 'Delivery', description: 'Deliver final logo package with all formats and guidelines.' },
    ],
    faq: [
      { question: 'How many logo concepts do I get?', answer: 'We provide 3-5 initial concepts. You choose one and we refine it with unlimited revisions.' },
      { question: 'What if I don\'t like any concepts?', answer: 'We\'ll create additional concepts based on your feedback at no extra cost.' },
      { question: 'Do you design other brand materials?', answer: 'Yes, we design business cards, letterheads, social media templates, and other brand collateral.' },
    ],
    platforms: [],
  },
  'listing-cataloging': {
    serviceName: 'Listing / Cataloging',
    heroDescription: 'SEO-optimized product listing and catalog management across all marketplaces.',
    overview: 'Professional product listing and catalog management services for Amazon, Flipkart, Meesho, JioMart and more. We create SEO-optimized listings with compelling copy that ranks higher and converts better.',
    features: [
      'SEO-optimized product titles and descriptions',
      'Backend keyword research and implementation',
      'Bullet points and feature highlighting',
      'Category and attribute optimization',
      'Bulk listing for large catalogs',
      'Multi-platform catalog sync',
    ],
    benefits: [
      { title: 'Higher Rankings', description: 'Keyword-optimized listings that rank higher in marketplace search results.', icon: 'Check' },
      { title: 'Better Conversions', description: 'Compelling copy and structured data that persuade shoppers to buy.', icon: 'Check' },
      { title: 'Time Savings', description: 'Upload hundreds of products efficiently with our bulk listing process.', icon: 'Check' },
      { title: 'Consistency', description: 'Uniform brand messaging and quality across all your marketplace listings.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Research', description: 'Keyword research and competitor analysis.' },
      { step: 2, title: 'Creation', description: 'Write optimized titles, bullets, and descriptions.' },
      { step: 3, title: 'Upload', description: 'Upload listings with proper categorization.' },
      { step: 4, title: 'Optimize', description: 'Monitor performance and refine listings.' },
    ],
    faq: [
      { question: 'How do you optimize listings?', answer: 'We use keyword research, competitor analysis, and conversion copywriting to create listings that rank and convert.' },
      { question: 'Can you handle bulk uploads?', answer: 'Yes, we can upload hundreds or thousands of products efficiently using bulk templates.' },
      { question: 'Do you create listings for all marketplaces?', answer: 'Yes, we create optimized listings for Amazon, Flipkart, Meesho, JioMart, AJIO, Nykaa, and Myntra.' },
    ],
    platforms: ['Amazon', 'Flipkart', 'Meesho', 'JioMart'],
  },
  'warehouse-facility': {
    serviceName: 'Warehouse Facility',
    heroDescription: 'Multi-channel warehouse and fulfillment support for eCommerce sellers.',
    overview: 'Centralized warehouse management and fulfillment support for multi-platform sellers. We help coordinate FBA prep, Flipkart Fulfillment (FKF), Meesho logistics, and self-ship operations for efficient inventory movement.',
    features: [
      'Multi-platform inventory management',
      'FBA prep and shipment services',
      'Flipkart Fulfillment coordination',
      'Quality control and inspection',
      'Order processing support',
      'Return processing assistance',
    ],
    benefits: [
      { title: 'Centralized Control', description: 'Manage inventory across all platforms from a single dashboard and process.', icon: 'Check' },
      { title: 'Faster Fulfillment', description: 'Streamlined operations mean faster order processing and happier customers.', icon: 'Check' },
      { title: 'Reduced Errors', description: 'Quality control processes minimize shipping errors and returns.', icon: 'Check' },
      { title: 'Cost Savings', description: 'Optimized logistics reduce shipping costs and operational overhead.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Assessment', description: 'Review current logistics and identify improvement areas.' },
      { step: 2, title: 'Setup', description: 'Implement inventory management system and processes.' },
      { step: 3, title: 'Operations', description: 'Manage daily fulfillment and inventory movements.' },
      { step: 4, title: 'Optimize', description: 'Continuous improvement of logistics efficiency.' },
    ],
    faq: [
      { question: 'Do you own warehouses?', answer: 'We partner with trusted warehouse providers and can help you set up your own facility.' },
      { question: 'Can you handle FBA prep?', answer: 'Yes, we provide complete FBA prep services including labeling, packaging, and shipment creation.' },
      { question: 'What platforms do you support?', answer: 'We support inventory management for Amazon, Flipkart, Meesho, JioMart, and your own website.' },
    ],
    platforms: ['Amazon', 'Flipkart', 'Meesho', 'JioMart'],
  },
  'seller-reinstatement': {
    serviceName: 'Seller Reinstatement',
    heroDescription: 'Expert appeal writing for suspended Amazon, Flipkart, Meesho, and JioMart accounts.',
    overview: 'Account suspended? Our reinstatement experts help you get back to selling quickly. We write compelling appeals, gather required documentation, and guide you through the reinstatement process for all major marketplaces.',
    features: [
      'Account suspension analysis',
      'Professional appeal letter writing',
      'Corrective action plan creation',
      'Document preparation and submission',
      'Follow-up communication support',
      'Prevention strategy consultation',
    ],
    benefits: [
      { title: 'Fast Recovery', description: 'Our expertly written appeals typically get faster responses and higher approval rates.', icon: 'Check' },
      { title: 'High Success Rate', description: 'We have a proven track record of successfully reinstating suspended seller accounts.', icon: 'Check' },
      { title: 'Expert Knowledge', description: 'Deep understanding of marketplace policies and what appeals teams look for.', icon: 'Check' },
      { title: 'Prevention Advice', description: 'Get guidance on avoiding future suspensions once your account is restored.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Analysis', description: 'Review suspension notice and identify root cause.' },
      { step: 2, title: 'Plan', description: 'Create corrective action plan and gather evidence.' },
      { step: 3, title: 'Appeal', description: 'Submit a professional, compelling appeal letter.' },
      { step: 4, title: 'Follow-up', description: 'Monitor response and provide additional information if needed.' },
    ],
    faq: [
      { question: 'How long does reinstatement take?', answer: 'It varies by platform and violation type, but typically ranges from a few days to 2-4 weeks.' },
      { question: 'What causes account suspension?', answer: 'Common reasons include policy violations, counterfeit claims, poor seller metrics, and verification issues.' },
      { question: 'Can all suspended accounts be reinstated?', answer: 'While we have a high success rate, some severe violations may result in permanent suspension. We\'ll give you an honest assessment upfront.' },
    ],
    platforms: ['Amazon', 'Flipkart', 'Meesho', 'JioMart'],
  },
  'product-photography': {
    serviceName: 'Product Photography',
    heroDescription: 'Professional product photography optimized for Amazon, Flipkart, and Meesho.',
    overview: 'High-quality product photography that makes your listings stand out. We offer white background shots, lifestyle photography, and 360-degree views — all optimized for marketplace requirements and maximum conversion impact.',
    features: [
      'White background (Amazon compliant) photography',
      'Lifestyle and contextual photography',
      'Image editing and retouching included',
      'Multiple angles per product',
      'Quick turnaround: 48-72 hours',
      'Infographic and comparison images',
    ],
    benefits: [
      { title: 'Higher Conversions', description: 'Professional photos significantly increase click-through and conversion rates.', icon: 'Check' },
      { title: 'Marketplace Compliant', description: 'All images meet Amazon, Flipkart, and Meesho technical requirements.', icon: 'Check' },
      { title: 'Brand Consistency', description: 'Uniform lighting, angles, and editing style across your entire catalog.', icon: 'Check' },
      { title: 'Fast Delivery', description: 'Quick 48-72 hour turnaround so you can list faster and start selling sooner.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Brief', description: 'Discuss photography requirements and style preferences.' },
      { step: 2, title: 'Shoot', description: 'Professional photography session with proper lighting and equipment.' },
      { step: 3, title: 'Edit', description: 'High-end retouching and color correction.' },
      { step: 4, title: 'Deliver', description: 'Receive optimized images in all required formats.' },
    ],
    faq: [
      { question: 'What types of photography do you offer?', answer: 'We offer white background, lifestyle, 360-degree, infographic, and comparison photography.' },
      { question: 'Do I need to send my products?', answer: 'Yes, you\'ll need to ship your products to our studio. We\'ll return them after the shoot.' },
      { question: 'How many photos per product?', answer: 'Typically 5-8 photos per product including different angles and lifestyle shots.' },
    ],
    platforms: ['Amazon', 'Flipkart', 'Meesho'],
  },
  'digital-marketing': {
    serviceName: 'Digital Marketing',
    heroDescription: 'Full-spectrum digital marketing — SEO, Google Ads, social media, and lead generation.',
    overview: 'Comprehensive digital marketing services to grow your brand online. From SEO and Google Ads to social media marketing and content strategy — we create data-driven campaigns that generate quality leads and drive revenue growth.',
    features: [
      'On-page and off-page SEO',
      'Google Ads (Search, Shopping, Display)',
      'Facebook & Instagram paid campaigns',
      'Content marketing and blog strategy',
      'Monthly analytics and reporting',
      'Conversion rate optimization',
    ],
    benefits: [
      { title: 'More Traffic', description: 'SEO and paid strategies that drive qualified visitors to your website and listings.', icon: 'Check' },
      { title: 'Better Leads', description: 'Targeted campaigns that attract customers ready to buy your products.', icon: 'Check' },
      { title: 'Measurable ROI', description: 'Clear reporting shows exactly what your marketing investment returns.', icon: 'Check' },
      { title: 'Scalable Growth', description: 'Campaigns designed to scale as your business grows and budgets increase.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Strategy', description: 'Develop comprehensive digital marketing strategy.' },
      { step: 2, title: 'Setup', description: 'Configure campaigns, tracking, and creative assets.' },
      { step: 3, title: 'Launch', description: 'Deploy campaigns across selected channels.' },
      { step: 4, title: 'Optimize', description: 'Continuous monitoring, testing, and improvement.' },
    ],
    faq: [
      { question: 'What channels do you manage?', answer: 'We manage SEO, Google Ads, Facebook/Instagram Ads, LinkedIn Ads, email marketing, and content marketing.' },
      { question: 'How long before I see SEO results?', answer: 'SEO typically shows meaningful results in 3-6 months. Paid ads can show results within days.' },
      { question: 'Do you offer monthly retainers?', answer: 'Yes, we offer flexible monthly packages based on channels managed and ad spend.' },
    ],
    platforms: [],
  },
  'enhance-brand-content': {
    serviceName: 'Enhance Brand Content (A+)',
    heroDescription: 'Premium A+ content and Brand Store creation for Amazon and Flipkart.',
    overview: 'Transform your product detail pages with rich A+ Content that tells your brand story, showcases product features, and increases conversions by up to 30%. We create stunning layouts with comparison charts, lifestyle imagery, and compelling copy.',
    features: [
      'Premium A+ Content modules for Amazon',
      'Rich media product descriptions',
      'Comparison charts and feature highlights',
      'Lifestyle imagery integration',
      'Brand story modules',
      'Flipkart Rich Content creation',
    ],
    benefits: [
      { title: 'Higher Conversions', description: 'A+ Content can increase conversion rates by 10-30% compared to standard listings.', icon: 'Check' },
      { title: 'Reduced Returns', description: 'Better product information helps customers make informed purchases, reducing returns.', icon: 'Check' },
      { title: 'Brand Storytelling', description: 'Tell your brand story in a visually compelling way that builds customer loyalty.', icon: 'Check' },
      { title: 'Competitive Advantage', description: 'Stand out from competitors with premium content that elevates your brand.', icon: 'Check' },
    ],
    process: [
      { step: 1, title: 'Strategy', description: 'Plan content modules based on product features and brand story.' },
      { step: 2, title: 'Design', description: 'Create visually stunning layouts with brand-consistent imagery.' },
      { step: 3, title: 'Content', description: 'Write compelling copy that highlights benefits and features.' },
      { step: 4, title: 'Submit', description: 'Submit to Amazon/Flipkart for approval and go live.' },
    ],
    faq: [
      { question: 'Do I need Brand Registry for A+ Content?', answer: 'Yes, Brand Registry is required for Amazon A+ Content. We can help you with the Brand Registry process.' },
      { question: 'How many modules can I include?', answer: 'Amazon allows up to 7 modules per ASIN. We recommend using 5-7 for maximum impact.' },
      { question: 'How long does A+ Content creation take?', answer: 'Typically 1-2 weeks depending on the number of ASINs and complexity of design.' },
    ],
    platforms: ['Amazon', 'Flipkart'],
  },
};
